### ISSUE TITLE
Feature Request: Team Avatars

### ISSUE THREAD

**Issue by Califon** [EnrgyzerBunny/trash-react#44]
Ability to upload Team Avatar imgs.

**Comment by EnrgyzerBunny** [comment]
notes:
- Explore hosting/upload flow
- if needed just allow for url to be submitted and api consumes it and enters into DB as a Team table field.

**Comment by EnrgyzerBunny** [comment]
would display on team page but where else? is it worth doing a miniversion on the leaderboards?

**Comment by EnrgyzerBunny** [comment]
azure blob storage provisioned and config for correct access levels

**Comment by EnrgyzerBunny** [comment]
Flow should likely be:

Upload
- on own Team page, option to edit/upload team pic
- makes auth api call to trash-api to get blob connection string (to prevent anyone not in the owner list from getting the con string)
- file picker input type
- use azure storage npm mod to upload the file with the con string (with overwrite if exists flagged), filename should be set to a static teamID based string to be predictable (e.g. "team-<ID>.png")

Fetch existing team pic
- cleanest method would probably be to call api for a team avatar endpoint, and have the api check the blob folder for possible team avatar pics and return the url. if not found then return the placeholder.

Should the upload flow when grabbing the con string wipe the current pic? this would make it safer to support different filetypes that may not get auto overwritten.

**Comment by EnrgyzerBunny** [comment]
team imgs are implemented - upload flow is not built, will split into new issue
